Add check for minimum disk size
This fixes issue 164, and changes:

  Failure: command execution error:
  Could not add os for instance instance2 on node node4:
  OS create script failed (exited with exit code 1), last lines in the log file:
  tar: ./bin/df: Cannot open: No such file or directory
  tar: ./bin/ip: Cannot open: No such file or directory
  tar: ./bin/grep: Cannot open: No such file or directory
  tar: ./opt: Cannot mkdir: No space left on device
  tar: ./selinux: Cannot mkdir: No space left on device
  tar: Exiting with failure status due to previous errors

Into:

  Failure: command execution error:
  Could not add os for instance instance2 on node node4:
  OS create script failed (exited with exit code 1), last lines in the log file:
  Device size is too small (128 MB)
  Required size is at least 256MB

Signed-off-by: Iustin Pop <iustin@google.com>
Reviewed-by: Bernardo Dal Seno <bdalseno@google.com>

diff --git a/create b/create
--- a/create
+++ b/create
@@ -19,6 +19,10 @@
 
 set -e
 
+# minimum device size is 256 MB, but we use 255 to account for
+# potential rounding
+declare -ri MIN_DEV_SIZE=$((255*1048576))
+
 . common.sh
 
 if [ "$GENERATE_CACHE" = "yes" -a ! -d "$CACHE_DIR" ]; then
@@ -36,6 +40,13 @@ if [ ! -b $blockdev ]; then
   CLEANUP+=("losetup -d $blockdev")
 fi
 
+DEVICE_SIZE=$(blockdev --getsize64 $blockdev)
+if [ "$DEVICE_SIZE" -lt $MIN_DEV_SIZE ]; then
+  echo "Device size is too small ($((DEVICE_SIZE/1048576)) MB)" 1>&2
+  echo "Required size is at least 256MB" 1>&2
+  exit 1
+fi
+
 if [ "$PARTITION_STYLE" = "none" ]; then
   filesystem_dev=$blockdev
 elif [ "$PARTITION_STYLE" = "msdos" ]; then
@@ -44,7 +55,7 @@ elif [ "$PARTITION_STYLE" = "msdos" ]; then
   filesystem_dev=$(map_disk0 $blockdev)
   CLEANUP+=("unmap_disk0 $blockdev")
 else
-  echo "Unknown partition style $PARTITION_STYLE"
+  echo "Unknown partition style $PARTITION_STYLE" 1>&2
   exit 1
 fi
 
