Report error when exporting non-ext partition
Report an error if it's exporting an instance fails because of the
wrong filesystem type.

This fixes issue 303.

Signed-off-by: Thomas Thrainer <thomasth@google.com>
Reviewed-by: Guido Trotter <ultrotter@google.com>

diff --git a/export b/export
--- a/export
+++ b/export
@@ -43,6 +43,9 @@ vol_type=$($VOL_TYPE $filesystem_dev)
 
 if [ "${vol_type:0:3}" = "ext" ]; then
   dump -0 -q -f - "$filesystem_dev"
+else
+  echo "Can't dump partition of type ${vol_type}!" >&2
+  exit 1
 fi
 
 # execute cleanups
